spring.application.name=attendance-tracker-backend

# MySQL Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/attendance
#spring.datasource.username=root
#spring.datasource.password=1234

spring.datasource.url=jdbc:mysql://136.243.19.21:3306/attendance
spring.datasource.username=attendance-user
spring.datasource.password=hAA14f69NMmWoKV

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server properties
server.port=8080
server.servlet.context-path=/api

#SMTP Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=slavko.ramljak@fsre.sum.ba
spring.mail.password=rxdq ynva sfgh rzyz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#TEMP DEBUG
logging.level.org.springframework.security=DEBUG